// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLD4nO-5T17rLPR2d9YKbMPFoZ6nJ2U2g',
    appId: '1:775580019570:web:b697e4a81e9dbd57d48beb',
    messagingSenderId: '775580019570',
    projectId: 'emaniti-fb63e',
    authDomain: 'emaniti-fb63e.firebaseapp.com',
    storageBucket: 'emaniti-fb63e.appspot.com',
    measurementId: 'G-LPRWVW6TNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9zhtd7WdHrBJDmAWRLlTfVNAsk13yF8',
    appId: '1:775580019570:android:06e81376d3bfd781d48beb',
    messagingSenderId: '775580019570',
    projectId: 'emaniti-fb63e',
    storageBucket: 'emaniti-fb63e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlkzmuC5GVncD7x7w4kKzg77qU96xZcE',
    appId: '1:775580019570:ios:2f83280450ae702bd48beb',
    messagingSenderId: '775580019570',
    projectId: 'emaniti-fb63e',
    storageBucket: 'emaniti-fb63e.appspot.com',
    iosClientId: '775580019570-0qerg4d24iho2gk0lc1k9admg75e1i1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlkzmuC5GVncD7x7w4kKzg77qU96xZcE',
    appId: '1:775580019570:ios:0f6771a45609969bd48beb',
    messagingSenderId: '775580019570',
    projectId: 'emaniti-fb63e',
    storageBucket: 'emaniti-fb63e.appspot.com',
    iosClientId: '775580019570-56bi133hvpr7cplligvvr2vd2ropotsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.application2.RunnerTests',
  );
}
